caracal-pipeline/caracal

caracal/workers/ddcal_worker.py
=> Rename the cubical cab.

caracal/sample_configurations/meerkat-continuum-defaults.yml, caracal/sample_configurations/meerkat-defaults.yml
Change the labels for the inspect worker to the ones appropriate for new workflow.
Fixes #1083 .
=> Fix meerkat configs

caracal/schema/crosscal_schema.yml
Bunch of typos and b_fillgaps missing from secondary in schema leading to errors when using secondary for bandpass.
=> Fix bug in cross call

caracal/workers/flag_worker.py
=> fix sanity check of channel selection in flag_spw

Jenkinsfile.sh
singularity hangs on a failed download. Switching to Docker until fixed upstream
=> switch to docker only testing

Jenkinsfile.sh, caracal/dispatch_crew/utils.py, caracal/workers/flag_worker.py, caracal/workers/line_worker.py, caratekit.sh
- Make caratekit more flexible w.r.t. local image archive (STIMELA_PULLFOLDER)
- Change Jenkinsfile accordingly
Resolves #1111
=> Fourth dan

caratekit.sh
This started out as a dummy to test Stimela compatibility, but there are actually 2 lines of description that changed.
=> Edited caratekit description

Jenkinsfile.sh, caracal/workers/line_worker.py, caratekit.sh
Some caratekit bugfixes, and merging issue-1189
=> Seventh dan second kata

caracal/sample_configurations/meerkat-defaults.yml, caracal/schema/getdata_schema.yml, caracal/workers/worker_administrator.py
=> Issue 1195

caracal/data/meerkat_files/flagtarget_V.rfis, caracal/workers/line_worker.py
Fixes issue with reading obsinfo of `_mst.ms` file in `line` worker.
=> obsinfo file of _mst.ms

caracal/schema/line_schema.yml, caracal/workers/line_worker.py
=> closes #1179

caracal/schema/flag_schema.yml, caracal/workers/selfcal_worker.py
As the title suggest, really minor changes.
Fixes #1241 and #1228.
=> Minor fixes

caracal/data/meerkat_files/firstpass_Q_sparsescans.rfis
this is just adding a new AOflagger strategy. Will merge without testing.
=> add AOflagger strategy for #1261

caratekit.sh
Resolves #1266 
Small but annoying bug for caratekit users.
=> Minor bugfixes

caracal/schema/crosscal_schema.yml, caracal/workers/crosscal_worker.py
Always render a png version of the gain table report if plotgains is turned on. Fixing issue #1279
=> Plotgain png

caracal/dispatch_crew/noisy.py, caracal/schema/line_schema.yml, caracal/workers/line_worker.py
This PR allows users to estimate the natural noise of the line cubes given Tsys/eff and the dish diameter. The implementation is a shameless copy-paste from https://github.com/paoloserra/noisy . The noise estimate is printed to log-caracal.txt .
With _some_ delay, this addresses #65 (closed long ago for lack of faith).
This PR also fixes some minor errors in the line worker.
=> predict noise of line cube

caracal/workers/inspect_worker.py
=> Correct issue #1285

caratekit.sh
Very minor fixes. The generated shell script was missing some lines and one line was printed one time too many.
=> Some cosmetics regarding the auto-shellscript

README.md
What it says on the title. Closes #625 .
=> Add instructions to install CARACal on ILIFU

caracal/workers/ddcal_worker.py
=> fixing labels and cleaning the postcal imaging function

README.md
Based on #1329, @healytwin1 's solution.
=> Change ILIFU install process

.github/workflows/test_installation.yml, README.md, setup.py
Updating the pip update command for tests to go smoothly.
=> Blind debugging

caracal/dispatch_crew/catalog_parser.py
=> Adjust for ridiculous CASA notation

caracal/workers/worker_administrator.py
=> Fixes #1365

caracal/schema/line_schema.yml, caracal/workers/line_worker.py
=> add option to make dirty PSF cube only

caracal/schema/crosscal_schema.yml, setup.py
Remove scan selection bad default
=> Fixes #1396

caracal/workers/line_worker.py, caracal/workers/transform_worker.py
=> Skip writing unnecessary flag versions in line worker

caracal/schema/line_schema.yml
related to https://github.com/ratt-ru/Stimela/issues/740
=> beam pars are floats

caracal/workers/utils/flag_Uzeros.py
=> fixes #1445

caracal/workers/ddcal_worker.py, setup.py
=> Update region module for ddcal

caracal/schema/line_schema.yml, caracal/workers/line_worker.py
=> Set minimum value of 1 for wscl_sofia_niter

caracal/schema/crosscal_schema.yml, caracal/schema/polcal_schema.yml, caracal/workers/crosscal_worker.py, caracal/workers/polcal_worker.py
=> Enabling setting the flux density to 1 Jy (unpolarized)

caracal/workers/prep_worker.py
=> uniform weights

caracal/schema/selfcal_schema.yml, caracal/workers/line_worker.py, caracal/workers/selfcal_worker.py
added a way to read the delay self-calibration solutions
=> 1619 set delay calibration as default in selfcal

caracal/workers/mosaic_worker.py
=> catch error when cubes to be mosaicked have a Stokes axis

caracal/workers/selfcal_worker.py
resolves https://github.com/caracal-pipeline/caracal/issues/1605
=> Issue 1605
