caracal/schema/flag_schema.yml
@svw26 your last comment was:
I don't want to mess up flag_schema.yml by pushing my own commit, so please just make sure that line 282 uses the following text:
desc: Ensure that the selected AOFlagger strategy is compatible with the type of correlations present in the input .MS file(s). E.g., attempts to flag on Stokes V for an .MS with XX and YY only will result in an error and CARACal exiting. The rules are 1. XY,YX must be present in order to flag on Stokes V,U (or on XY,YX), and 2. XX,YY must be present in order to flag on Stokes I,Q (or on XX,YY). Disable this parameter only if you know what you are doing.
"only thing left" in terms of what I could find in the space of 40 minutes this morning.
=> typos_sarah2

caracal/dispatch_crew/utils.py
At least GMRT data can give a negative direction in the json file for `DELAY_DIR`. This allows for correct matching.
=> Allow for negative RA direction in calibrators

caracal/workers/selfcal_worker.py
When using SoFiA as a clean mask, the wrong entry of the  `cleanmask_<something>` parameters is used at the various iterations. Basically, the (i-1)th entry is  used instead of the i-th entry. This is of course only noticeable when the values of those parameters is  not the same for all iterations. This PR fixes this problem.
=> fix sofia masking mismatch

caracal/sample_configurations/meerkat-defaults.yml
PR changes the flag__1 worker input label to 'cal' for the meerkat defaults - otherwise flags the _original_ ms, not cal datasets. This is potentially pretty dangerous since the AOFlagger strategies perform an '' OR" with preexisting flags - leading the later flag__2 to possibly overflag, not to mention calibrators won't be flagged at all.
=> Change flag label

caracal/sample_configurations/carateConfig.yml, caracal/sample_configurations/meerkat-continuum-defaults.yml, caracal/sample_configurations/meerkat-defaults.yml, caracal/sample_configurations/minimalConfig.yml, caracal/sample_configurations/minitestConfig.yml, caracal/sample_configurations/workflow_new.yml, caracal/schema/inspect_schema.yml, caracal/workers/inspect_worker.py
Inspect worker has been updated to
- be able inspect target or any calibrator visibilities in the original as well as splitted datasets (issue #1122 ) via setting inspect.field (issue #1096)
- label_cal has been changed to label_plot to make it more intuitive (issue #1103)
I removed individual field selections per plot type. It can only plot targets OR calibrators, requiring repeated inspect worker runs (which however doesn't lead to a significant overhead as per our discussion under issue #1122). Users can also select e.g. field: 'gcal' for plotting specific fields. However, if user selects different intents that belong to the same field (e.g. fcal and bpcal), it will lead to duplicate plots of these fields with different intents as labels in their name (which had been the case before my …
=> Inspect target in original and splitted data

caracal/workers/inspect_worker.py
This PR:
- changes the name of the standard plots to be consistent with those of the new shadems plots;
- when `field = calibrators`, plot `bpcal` and `gcal` but NOT `fcal`, which would be the same as `bpcal` (that's an underlying assumption in the `crosscal` worker so I think we should use it consistently throughout the pipeline).
=> avoid repeated plots and use better standard plot names

caracal/sample_configurations/carateConfig.yml, caracal/schema/selfcal_schema.yml, caracal/workers/selfcal_worker.py, setup.py
Fix #1140 by:
- forcing the regridded mask to be of integer type
- anyway  do not overwrite the user input mask with the regridded one
I've also cleaned up a bit that part of the `selfcal` worker.
Fix #1139 by lowering the default memory fraction to 0.05.
=> Some fixes for CARACal v1.0.3

caracal/workers/selfcal_worker.py
I think the agreement was to always use wsclean 2.9, also when multiscale is ON. This is what this PR does.
=> wsclean 2.9 also when multiscale clean is ON

Jenkinsfile.sh, caratekit.sh
Reinstate Singularity Jenkins test without the need for > v3.5 Singularity. Notice that this will not alter the Singularity cache dir, which may be anywhere.
=> Reinstate singularity Jenkins test

caracal/dispatch_crew/config_parser.py, caracal/workers/worker_administrator.py
* no more confusing messages (famous last words)
* for list-type variables, support ``--section-variable x,y,z`` on the command line. This is consistent with the yml syntax (the old code needed one to specify ``--section-variable`` multiple times to make a list).
=> fixes #1112 and cleans up command-line parser, a little

caracal/schema/crosscal_schema.yml, caracal/workers/crosscal_worker.py
- Fixes #1204
- Fixes #1206 
- Use I,Q,U,v = (1,0,0,0) model when `I` is specified but imaging has not been done
=> Issue 1204

caracal/workers/selfcal_worker.py
SoFiA used to run even when imaging and calibration were turned off in the selfcal worker, causing unnecessary overhead when using selfcal worker only to transfer models and gains to a high spectral res ms. Alas no more!
=> sofia quick fix

caracal/workers/prep_worker.py
A case of the bad indent, which messes up the rephasing to correct calibrator coordinates in the prep worker.
Due to the incorrect indent the loop over calibrators does not run, making the rephasing impossible.
This PR fixes it.
=> Fix indent error

caracal/sample_configurations/meerkat-continuum-defaults.yml, caracal/sample_configurations/meerkat-defaults.yml
Band rolloff does not seem to be flagged by the calflag mode of either applycal or mstransform; resulting in the target data looking like this:
While I have no idea why this happens, I am adding a temporary fix by enabling flag_spw in flag__2 for the meerkat configs (which are the only configs to lack it anyway).
=> Stopgap flagging 

caracal/schema/line_schema.yml, caracal/workers/line_worker.py
Some users are interested in setting the shape of the restoring beam for spectral line cubes. This is already possible  in WSClean so it was just a matter of adding the relevant parameter in the line worker and schema. I've made and tested this change, and it seems to work. @HaoChen-ast please give this a try.
=> user-defined restoring beam for spectral-line cubes

caracal/schema/flag_schema.yml, caracal/workers/flag_worker.py
Once binning in channels datacubes show horizontal striping.
This is similar to what seen by Mario Santos in the power spectrum of MeerKAT's visibilities, and is due to some RFI? at u=0 and over all values of v.
as seen in this FFT the 'striped' datacube
Hence we add a module that flags (using casacore) in the U coordinate given a certain range.
=> flag within a range of u coordinates

caracal/schema/crosscal_schema.yml, caracal/workers/crosscal_worker.py
Fixes #1391 (workaround for SPR1-1177 - mislabelling of tracking scans in katdal). This adds the ability to deselect scans
when solving (note not necessarily applying - user should still flag those scans). It is however essential to flag them to avoid interpolated solution being flagged and unnecessarily flagging transfer scans
@Sinah-astro please use this branch for now
=> Scan selection on solvers

caracal/workers/line_worker.py
The `line` worker was still saving a `before_worker` flag version after rewinding to a user-specified version even when the flags were not going to be edited further. That should be fixed now.
=> fixed remaining flaw in flag version logic of line worker

caracal/workers/line_worker.py
@dane-kleiner and I spotted this possible error. The `int()` call results in a mask regridded by Montage to a header with CRPIX2 = 600.5 being modified to CRPIX2 = 601 after adding a single Y layer. In fact, it should have been modified to CRPIX2 = 601.5. This bug results in a small but noticeable WCS offset.
Note that this only happens when the regridded mask needs to be added X or Y layers (which is the case sometimes, although I don't remember why...)
@molnard89 please check that this fix is correct.
=> Fix small bug in line mask regridding

caracal/workers/line_worker.py
As discussed in #1209  , even though there are default units, the FITS standard document recommends explicitly stating the units in the header. This PR does that.
The cubes made by WSclean are in frequency and have CUNIT3 = Hz in the header. When converting to velocity CARACal deletes CUNIT3. This PR changes that behaviour, and changes CUNIT3 from Hz to m/s when converting the axis. If the reverse conversion is requested, CUNIT3 changes from m/s to Hz.
=> fix issue 1209
